"use strict";
const http=require("http"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const PORT=Number(process.env.PORT||8080),DATA_DIR=process.env.DATA_DIR||"/app/data";
const VAULT_FILE=path.join(DATA_DIR,"vault.json"),LEGACY_FILE=path.join(DATA_DIR,"clips.json"),UPLOAD_DIR=path.join(DATA_DIR,"uploads"),MAX_BODY=10*1024*1024,MAX_UPLOAD=50*1024*1024;
const ADMIN_USERNAME=process.env.APP_USERNAME||"admin",ADMIN_PASSWORD=process.env.APP_PASSWORD,SESSION_SECRET=process.env.SESSION_SECRET,ESCROW_KEY=process.env.ESCROW_KEY;
if(!ADMIN_PASSWORD||ADMIN_PASSWORD.length<12||!SESSION_SECRET||SESSION_SECRET.length<32||!ESCROW_KEY||ESCROW_KEY.length<32)throw new Error("APP_PASSWORD, SESSION_SECRET, and ESCROW_KEY are required");
fs.mkdirSync(DATA_DIR,{recursive:true});fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const secret=Buffer.from(SESSION_SECRET,"utf8"),escrowSecret=crypto.createHash("sha256").update(ESCROW_KEY).digest();
function sealEscrow(raw){const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",escrowSecret,iv),ct=Buffer.concat([c.update(raw,"base64url"),c.final()]);return{iv:iv.toString("base64url"),tag:c.getAuthTag().toString("base64url"),ciphertext:ct.toString("base64url")}}
function unsealEscrow(e){try{const d=crypto.createDecipheriv("aes-256-gcm",escrowSecret,Buffer.from(e.iv,"base64url"));d.setAuthTag(Buffer.from(e.tag,"base64url"));return Buffer.concat([d.update(Buffer.from(e.ciphertext,"base64url")),d.final()]).toString("base64url")}catch{return null}}
const hashPassword=(password,salt=crypto.randomBytes(16).toString("hex"))=>({salt,passwordHash:crypto.pbkdf2Sync(password,salt,210000,32,"sha256").toString("hex")});
const passwordMatches=(password,user)=>crypto.timingSafeEqual(Buffer.from(hashPassword(password,user.salt).passwordHash,"hex"),Buffer.from(user.passwordHash,"hex"));
const safeEqual=(a,b)=>a.length===b.length&&crypto.timingSafeEqual(a,b);
let vault;
try{vault=JSON.parse(fs.readFileSync(VAULT_FILE,"utf8"));}catch{let legacy=[];try{legacy=JSON.parse(fs.readFileSync(LEGACY_FILE,"utf8"));}catch{}const p=hashPassword(ADMIN_PASSWORD),now=new Date().toISOString();vault={users:[{id:"admin",username:ADMIN_USERNAME,role:"admin",...p,createdAt:now}],clips:legacy.map(c=>({...c,ownerId:"admin",sharedWith:[]})),uploads:[]};}
if(!Array.isArray(vault.users)||!Array.isArray(vault.clips))throw new Error("Invalid vault data");if(!Array.isArray(vault.uploads))vault.uploads=[];
function save(){fs.writeFileSync(VAULT_FILE+".tmp",JSON.stringify(vault,null,2));fs.renameSync(VAULT_FILE+".tmp",VAULT_FILE);}
function userById(id){return vault.users.find(u=>u.id===id)}function userByName(username){return vault.users.find(u=>u.username.toLowerCase()===String(username).toLowerCase())}
function publicUser(u,includeVaultKey=false){return {id:u.id,username:u.username,role:u.role,...(includeVaultKey?{vaultKey:u.vaultKey||null,escrowKey:u.escrowKey?unsealEscrow(u.escrowKey):null}:{}),createdAt:u.createdAt}}
function sessionToken(userId){const expiry=Date.now()+1000*60*60*24*14,payload=`${userId}.${expiry}`,sig=crypto.createHmac("sha256",secret).update(payload).digest("base64url");return `${payload}.${sig}`}
function currentUser(req){const m=(req.headers.cookie||"").match(/(?:^|;\s*)clip_session=([^;]+)/);if(!m)return null;const[id,expiry,sig]=m[1].split(".");if(!id||!expiry||!sig||!/^\d+$/.test(expiry)||Number(expiry)<Date.now())return null;const expected=crypto.createHmac("sha256",secret).update(`${id}.${expiry}`).digest("base64url");return safeEqual(Buffer.from(sig),Buffer.from(expected))?userById(id):null}
function respond(res,status,body,headers={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(JSON.stringify(body))}
function readJson(req){return new Promise((resolve,reject)=>{let b="",n=0;req.on("data",c=>{n+=c.length;if(n>MAX_BODY){reject(Error("Payload exceeds 10 MB"));req.destroy()}else b+=c});req.on("end",()=>{try{resolve(JSON.parse(b||"{}"))}catch{reject(Error("Invalid JSON"))}});req.on("error",reject)})}
function readRaw(req,limit=MAX_UPLOAD){return new Promise((resolve,reject)=>{const chunks=[];let n=0;req.on("data",c=>{n+=c.length;if(n>limit){reject(Error("File exceeds 50 MB"));req.destroy()}else chunks.push(c)});req.on("end",()=>resolve(Buffer.concat(chunks)));req.on("error",reject)})}
function publicUpload(a){return{id:a.id,name:a.name,mime:a.mime,size:a.size,url:"/api/files/"+a.id,encrypted:!!a.encrypted}}
function publicClip(c,viewer){const owner=userById(c.ownerId);if(c.encrypted)return{id:c.id,encrypted:true,envelope:c.envelope,attachments:(c.attachments||[]).map(id=>vault.uploads.find(a=>a.id===id)).filter(Boolean).map(publicUpload),createdAt:c.createdAt,updatedAt:c.updatedAt,owner:owner?.username||"Unknown",isOwner:c.ownerId===viewer.id,sharedWith:[]};return{id:c.id,title:c.title,type:c.type,content:c.content,image:c.image,attachments:(c.attachments||[]).map(id=>vault.uploads.find(a=>a.id===id)).filter(Boolean).map(publicUpload),createdAt:c.createdAt,updatedAt:c.updatedAt,owner:owner?.username||"Unknown",isOwner:c.ownerId===viewer.id,sharedWith:c.ownerId===viewer.id?(c.sharedWith||[]).map(id=>userById(id)?.username).filter(Boolean):[]}}
function canSee(c,user){return c.encrypted?c.ownerId===user.id:(c.ownerId===user.id||(c.sharedWith||[]).includes(user.id))}
function requireOwner(c,user,res){if(!c){respond(res,404,{error:"Clip not found"});return false}if(c.ownerId!==user.id){respond(res,403,{error:"Only the clip owner can change this"});return false}return true}
function validEnvelope(e){return !!e&&typeof e==="object"&&e.version===1&&e.alg==="AES-GCM"&&typeof e.iv==="string"&&/^[A-Za-z0-9_-]{16}$/.test(e.iv)&&typeof e.ciphertext==="string"&&/^[A-Za-z0-9_-]+$/.test(e.ciphertext)&&e.ciphertext.length>=22&&e.ciphertext.length<=MAX_BODY}
function attachmentIds(input,user,encrypted=false){if(!Array.isArray(input)||input.length>10)throw Error("Attach up to 10 files");const ids=[...new Set(input.map(String))];if(ids.some(id=>{const a=vault.uploads.find(a=>a.id===id);return !a||a.ownerId!==user.id||(encrypted&&!a.encrypted)}))throw Error("Invalid attachment");return ids}
const html=fs.readFileSync(path.join(__dirname,"public","index.html")),css=fs.readFileSync(path.join(__dirname,"public","style.css")),js=fs.readFileSync(path.join(__dirname,"public","app.js"));
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||"localhost"}`),headers={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer","Content-Security-Policy":"default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; img-src 'self' data: blob:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'"};Object.entries(headers).forEach(([k,v])=>res.setHeader(k,v));
if(req.method==="GET"&&u.pathname==="/"){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});return res.end(html)}if(req.method==="GET"&&u.pathname==="/style.css"){res.writeHead(200,{"Content-Type":"text/css; charset=utf-8","Cache-Control":"public, max-age=3600"});return res.end(css)}if(req.method==="GET"&&u.pathname==="/app.js"){res.writeHead(200,{"Content-Type":"application/javascript; charset=utf-8","Cache-Control":"public, max-age=3600"});return res.end(js)}
if(req.method==="POST"&&u.pathname==="/api/login")try{const{username="",password=""}=await readJson(req),user=userByName(username);if(!user||!passwordMatches(String(password),user))return respond(res,401,{error:"Invalid username or password"});return respond(res,200,{user:publicUser(user)},{"Set-Cookie":`clip_session=${sessionToken(user.id)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=1209600`})}catch(e){return respond(res,400,{error:e.message})}
if(req.method==="POST"&&u.pathname==="/api/logout")return respond(res,200,{ok:true},{"Set-Cookie":"clip_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"});
const user=currentUser(req);if(!user)return respond(res,401,{error:"Authentication required"});
if(req.method==="POST"&&u.pathname==="/api/uploads")try{const encrypted=req.headers["x-clip-encrypted"]==="1",data=await readRaw(req);if(!data.length)throw Error("Empty file");const a={id:crypto.randomUUID(),name:encrypted?"encrypted-attachment.bin":String(req.headers["x-file-name"]||"upload").replace(/[^a-zA-Z0-9._ -]/g,"_").slice(0,180),mime:encrypted?"application/octet-stream":String(req.headers["content-type"]||"application/octet-stream").split(";")[0],size:data.length,encrypted,ownerId:user.id,createdAt:new Date().toISOString()};fs.writeFileSync(path.join(UPLOAD_DIR,a.id),data);vault.uploads.push(a);save();return respond(res,201,publicUpload(a))}catch(e){return respond(res,400,{error:e.message})}
const fileMatch=u.pathname.match(/^\/api\/files\/([\w-]+)$/);if(fileMatch&&req.method==="GET"){const a=vault.uploads.find(x=>x.id===fileMatch[1]),clip=vault.clips.find(c=>(c.attachments||[]).includes(fileMatch[1]));if(!a||!clip||!canSee(clip,user)||(clip.encrypted&&clip.ownerId!==user.id))return respond(res,404,{error:"File not found"});res.writeHead(200,{"Content-Type":a.mime,"Content-Length":a.size,"Content-Disposition":`${a.encrypted?"attachment":"inline"}; filename="${a.name.replace(/"/g,"")}"`});return fs.createReadStream(path.join(UPLOAD_DIR,a.id)).pipe(res)}
if(req.method==="POST"&&u.pathname==="/api/vault-key")try{if(user.vaultKey)return respond(res,409,{error:"Vault already initialized"});const{wrappedKey}=await readJson(req);if(!validEnvelope(wrappedKey))throw Error("Invalid wrapped vault key");user.vaultKey=wrappedKey;save();return respond(res,201,{ok:true})}catch(e){return respond(res,400,{error:e.message})}
if(req.method==="POST"&&u.pathname==="/api/vault-escrow")try{const{vaultKey}=await readJson(req);if(typeof vaultKey!=="string"||!/^[A-Za-z0-9_-]{43}$/.test(vaultKey))throw Error("Invalid vault key");user.escrowKey=sealEscrow(vaultKey);save();return respond(res,200,{ok:true})}catch(e){return respond(res,400,{error:e.message})}
if(req.method==="GET"&&u.pathname==="/api/me")return respond(res,200,publicUser(user,true));
if(req.method==="POST"&&u.pathname==="/api/me/password")try{const{currentPassword="",newPassword=""}=await readJson(req);if(!passwordMatches(String(currentPassword),user))return respond(res,401,{error:"Current password is incorrect"});if(String(newPassword).length<12)return respond(res,400,{error:"Use a password with at least 12 characters"});Object.assign(user,hashPassword(String(newPassword)));save();return respond(res,200,{ok:true})}catch(e){return respond(res,400,{error:e.message})}
if(req.method==="GET"&&u.pathname==="/api/shareable-users")return respond(res,200,vault.users.filter(x=>x.id!==user.id).map(x=>publicUser(x)));
if(req.method==="GET"&&u.pathname==="/api/clips")return respond(res,200,vault.clips.filter(c=>canSee(c,user)).map(c=>publicClip(c,user)));
if(req.method==="POST"&&u.pathname==="/api/clips"&&req.headers["x-clip-encrypted"]==="1")try{const{envelope,attachments=[]}=await readJson(req);if(!validEnvelope(envelope))throw Error("Invalid encrypted clip");const now=new Date().toISOString(),clip={id:crypto.randomUUID(),encrypted:true,envelope,attachments:attachmentIds(attachments,user,true),ownerId:user.id,sharedWith:[],createdAt:now,updatedAt:now};vault.clips.unshift(clip);save();return respond(res,201,publicClip(clip,user))}catch(e){return respond(res,400,{error:e.message})}
if(req.method==="POST"&&u.pathname==="/api/clips")return respond(res,409,{error:"New clips must be end-to-end encrypted"});
const clipMatch=u.pathname.match(/^\/api\/clips\/([\w-]+)$/),shareMatch=u.pathname.match(/^\/api\/clips\/([\w-]+)\/shares$/),receivedMatch=u.pathname.match(/^\/api\/clips\/([\w-]+)\/received$/);
if(shareMatch&&req.method==="PUT")try{const clip=vault.clips.find(c=>c.id===shareMatch[1]);if(!requireOwner(clip,user,res))return;if(clip.encrypted)return respond(res,409,{error:"End-to-end encrypted clips cannot be shared"});const{userIds=[]}=await readJson(req);if(!Array.isArray(userIds)||userIds.some(id=>!userById(id)||id===user.id))throw Error("Invalid sharing selection");clip.sharedWith=[...new Set(userIds)];clip.updatedAt=new Date().toISOString();save();return respond(res,200,publicClip(clip,user))}catch(e){return respond(res,400,{error:e.message})}
if(clipMatch&&req.method==="PUT"&&req.headers["x-clip-encrypted"]==="1")try{const clip=vault.clips.find(c=>c.id===clipMatch[1]);if(!requireOwner(clip,user,res))return;if(!clip.encrypted)return respond(res,409,{error:"Legacy clips cannot be converted by this endpoint"});const{envelope,attachments=[]}=await readJson(req);if(!validEnvelope(envelope))throw Error("Invalid encrypted clip");Object.assign(clip,{envelope,attachments:attachmentIds(attachments,user,true),sharedWith:[],updatedAt:new Date().toISOString()});save();return respond(res,200,publicClip(clip,user))}catch(e){return respond(res,400,{error:e.message})}
if(clipMatch&&req.method==="PUT")try{const clip=vault.clips.find(c=>c.id===clipMatch[1]);if(!requireOwner(clip,user,res))return;return respond(res,409,{error:"Legacy plaintext clips are read-only; create an encrypted replacement"})}catch(e){return respond(res,400,{error:e.message})}
if(receivedMatch&&req.method==="DELETE"){const clip=vault.clips.find(c=>c.id===receivedMatch[1]);if(!clip||clip.ownerId===user.id||!(clip.sharedWith||[]).includes(user.id))return respond(res,404,{error:"Shared clip not found"});clip.sharedWith=clip.sharedWith.filter(id=>id!==user.id);clip.updatedAt=new Date().toISOString();save();return respond(res,200,{ok:true})}
if(clipMatch&&req.method==="DELETE"){const clip=vault.clips.find(c=>c.id===clipMatch[1]);if(!requireOwner(clip,user,res))return;vault.clips=vault.clips.filter(c=>c.id!==clip.id);save();return respond(res,200,{ok:true})}
if(user.role!=="admin")return respond(res,403,{error:"Administrator access required"});
if(req.method==="GET"&&u.pathname==="/api/users")return respond(res,200,vault.users.map(x=>publicUser(x)));
if(req.method==="POST"&&u.pathname==="/api/users")try{const{username="",password="",role="user"}=await readJson(req),name=String(username).trim();if(!/^[a-zA-Z0-9_.-]{3,32}$/.test(name))throw Error("Username must be 3–32 characters: letters, numbers, . _ or -");if(userByName(name))throw Error("That username already exists");if(String(password).length<12)throw Error("Use a password with at least 12 characters");if(!["user","admin"].includes(role))throw Error("Invalid role");const newUser={id:crypto.randomUUID(),username:name,role,...hashPassword(String(password)),createdAt:new Date().toISOString()};vault.users.push(newUser);save();return respond(res,201,publicUser(newUser))}catch(e){return respond(res,400,{error:e.message})}
const userMatch=u.pathname.match(/^\/api\/users\/([\w-]+)$/),resetMatch=u.pathname.match(/^\/api\/users\/([\w-]+)\/password$/);
if(resetMatch&&req.method==="PUT")try{const target=userById(resetMatch[1]),{newPassword=""}=await readJson(req);if(!target)return respond(res,404,{error:"User not found"});if(String(newPassword).length<12)return respond(res,400,{error:"Use a password with at least 12 characters"});Object.assign(target,hashPassword(String(newPassword)));save();return respond(res,200,{ok:true})}catch(e){return respond(res,400,{error:e.message})}
if(userMatch&&req.method==="DELETE"){const target=userById(userMatch[1]);if(!target)return respond(res,404,{error:"User not found"});if(target.id===user.id)return respond(res,400,{error:"You cannot delete your own account"});vault.users=vault.users.filter(x=>x.id!==target.id);vault.clips.forEach(c=>{c.sharedWith=(c.sharedWith||[]).filter(id=>id!==target.id)});save();return respond(res,200,{ok:true})}return respond(res,404,{error:"Not found"})}).listen(PORT,"0.0.0.0",()=>console.log(`Clipvault listening on ${PORT}`));
